name: Release

on:
  push:
    tags:
      - "v[0-9].*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image
    steps:
      - name: 🚀 Release new version
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
